language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'

install:
  - npm install

script: npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master